### PR TITLE
Support optionality of fields in rust

### LINKED ISSUE #4: Optionallness should be taken into account for fields
It looks like Java's generator treats the absence of either `required` or `optional` as `required`, for reference.

### PR DESCRIPTION
**Pull request by sfackler**
Like Java, a field with no requiredness is treated as required.

Closes #4

The setup with `should_encode` is a bit crummy - it'd be nice if the `encode` call could handle all the logic itself but I didn't want to restructure too much.

### CODE REVIEW

**Comment by sfackler** [comment]
Now also implements CompactProtocol because I didn't feel like switching branches :P

**Comment by reem** [comment]
Commenting what we discussed on IRC for the history: CompactProtocol has a bug (?) so I should hold this for a bit.

**Comment by reem** [comment]
Otherwise this looks great.

**Comment by reem** [comment]
@sfackler I'd like to land the optionality improvements even if the CompactProtocol is still buggy, can you perchance split this PR up?

**Comment by sfackler** [comment]
Yeah, I can cherry-pick that stuff over to another branch.

**Comment by sfackler** [comment]
Continued in #7 without the compact protocol for now

**Pull request closed without merging**
